package org.fbreader.fbreader;

public interface ActionCode {
	// please, don't change these numbers
	// add new action id's at the end of this list
	int NONE = 0;
	int SHOW_COLLECTION = 1;
	int SHOW_OPTIONS = 2;
	int UNDO = 3;
	int REDO = 4;
	int SHOW_CONTENTS = 5;
	int SEARCH = 6;
	int FIND_PREVIOUS = 7;
	int FIND_NEXT = 8;
	int LARGE_SCROLL_FORWARD = 9;
	int LARGE_SCROLL_BACKWARD = 10;
	int SMALL_SCROLL_FORWARD = 11;
	int SMALL_SCROLL_BACKWARD = 12;
	int MOUSE_SCROLL_FORWARD = 13;
	int MOUSE_SCROLL_BACKWARD = 14;
	int SCROLL_TO_HOME = 15;
	int SCROLL_TO_START_OF_TEXT = 16;
	int SCROLL_TO_END_OF_TEXT = 17;
	int CANCEL = 18;
	int INCREASE_FONT = 19;
	int DECREASE_FONT = 20;
	int SHOW_HIDE_POSITION_INDICATOR = 21;
	int TOGGLE_FULLSCREEN = 22;
	int FULLSCREEN_ON = 23;
	int ADD_BOOK = 24;
	int SHOW_BOOK_INFO = 25;
	int SHOW_HELP = 26;
	int ROTATE_SCREEN = 27;
	int SHOW_LAST_BOOKS = 28;
	int QUIT = 29;
	int OPEN_PREVIOUS_BOOK = 30;
	int FINGER_TAP_SCROLL_FORWARD = 31;
	int FINGER_TAP_SCROLL_BACKWARD = 32;
	int GOTO_NEXT_TOC_SECTION = 33;
	int GOTO_PREVIOUS_TOC_SECTION = 34;
	int COPY_SELECTED_TEXT_TO_CLIPBOARD = 35;
	int CLEAR_SELECTION = 36;
	int OPEN_SELECTED_TEXT_IN_DICTIONARY = 37;
};
